=== Tiltaments/Benelli.Alessandro.Palestra_648/catalogo.dtd
<!ELEMENT catalogo (corso*)>
<!ELEMENT corso (titolo, descrizione, immagine, intensita, prezzo_crediti, disponibile, edizioni)>
<!ATTLIST corso 
    id ID #REQUIRED
    categoria (corso | abbonamento | lezione_privata) #REQUIRED>
<!ELEMENT titolo (#PCDATA)>
<!ELEMENT descrizione (#PCDATA)>
<!ELEMENT immagine (#PCDATA)>
<!ELEMENT intensita (#PCDATA)>
<!ELEMENT prezzo_crediti (#PCDATA)>
<!ELEMENT disponibile (#PCDATA)>
<!ELEMENT edizioni (edizione*)>
<!ELEMENT edizione EMPTY>
<!ATTLIST edizione 
    id_edizione ID #REQUIRED
    trainer CDATA #REQUIRED
    giorni CDATA #IMPLIED
    orario CDATA #IMPLIED
    disponibile (true | false) "true">

=== Tiltaments/Benelli.Alessandro.Palestra_648/catalogo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalogo SYSTEM "catalogo.dtd">
<catalogo>
    <corso id="CRS01" categoria="corso">
        <titolo>Corso Avanzato Calisthenics</titolo>
        <descrizione>Corso intensivo di ginnastica a corpo libero per atleti intermedi e avanzati con progressioni su anelli e sbarra.</descrizione>
        <immagine>img/calisthenics.jpg</immagine>
        <intensita>alta</intensita>
        <prezzo_crediti>60</prezzo_crediti>
        <disponibile>true</disponibile>
        <edizioni>
            <edizione id_edizione="ED_01_A" trainer="Marco Trainer" giorni="Giov" orario="15:00" disponibile="true"/>
            <edizione id_edizione="ED_01_B" trainer="Luca Trainer" giorni="Sab" orario="19:00" disponibile="true"/>
        </edizioni>
    </corso>
    <corso id="CRS02" categoria="abbonamento">
        <titolo>Abbonamento Open Sala Pesi 3 Mesi</titolo>
        <descrizione>Accesso completo e illimitato alla sala pesi, area cardio e spogliatoi con armadietto riservato per un trimestre.</descrizione>
        <immagine>img/sala_pesi.jpg</immagine>
        <intensita>media</intensita>
        <prezzo_crediti>120</prezzo_crediti>
        <disponibile>true</disponibile>
        <edizioni>
            <edizione id_edizione="ED_02_A" trainer="Andrea Trainer" giorni="Lun,Mer,Ven" orario="17:00" disponibile="true"/>
        </edizioni>
    </corso>
    <corso id="CRS03" categoria="corso">
        <titolo>Posturale &amp; Mobilit&#224; Articolare</titolo>
        <descrizione>Esercizi a basso impatto mirati al riallineamento posturale, flessibilit&#224; della colonna e prevenzione infortuni.</descrizione>
        <immagine>img/posturale.jpg</immagine>
        <intensita>bassa</intensita>
        <prezzo_crediti>45</prezzo_crediti>
        <disponibile>true</disponibile>
        <edizioni>
            <edizione id_edizione="ED_03_A" trainer="Sara Trainer" giorni="Mer, Giov" orario="12:00" disponibile="true"/>
        </edizioni>
    </corso>
    <corso id="CRS04" categoria="lezione_privata">
        <titolo>Lezione Privata di Personal Training</titolo>
        <descrizione>Sessione individuale con un personal trainer per obiettivi specifici, allenamento personalizzato e monitoraggio dei progressi.</descrizione>
        <immagine>img/personal_trainer.jpg</immagine>
        <intensita>bassa</intensita>
        <prezzo_crediti>80</prezzo_crediti>
        <disponibile>true</disponibile>
        <edizioni>
            <edizione id_edizione="ED_04_A" trainer="Mario Trainer" giorni="Lun" orario="18:00-19:30" disponibile="true"/>
            <edizione id_edizione="ED_04_B" trainer="Luisa Trainer" giorni="Mer" orario="18:00-19:30" disponibile="true"/>
        </edizioni>
    </corso>
</catalogo>
