=== Tiltaments/Benelli.Alessandro.Palestra_648/data-init/promozioni.dtd
<!ELEMENT elenco_promozioni (promozione*)>
<!ELEMENT promozione (titolo, tipo, valore, criterio_applicazione, data_inizio, data_fine, corsi_applicati)>
<!ATTLIST promozione id_promo ID #REQUIRED>
<!ELEMENT titolo (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT valore (#PCDATA)>
<!ELEMENT criterio_applicazione (#PCDATA)>
<!ATTLIST criterio_applicazione 
    tipo_criterio (anzianita | spesa_pregressa | reputazione | indiscriminato) #REQUIRED
    soglia CDATA #IMPLIED>
<!ELEMENT data_inizio (#PCDATA)>
<!ELEMENT data_fine (#PCDATA)>
<!ELEMENT corsi_applicati (id_corso+)>
<!ELEMENT id_corso (#PCDATA)>

=== Tiltaments/Benelli.Alessandro.Palestra_648/promozioni.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE elenco_promozioni SYSTEM "promozioni.dtd">
<elenco_promozioni>
  <promozione id_promo="PR_LANCIO">
    <titolo>Sconto Lancio</titolo>
    <tipo>sconto</tipo>
    <valore>15</valore>
    <criterio_applicazione tipo_criterio="indiscriminato">tutti</criterio_applicazione>
    <data_inizio>2026-08-01</data_inizio>
    <data_fine>2027-12-31</data_fine>
    <corsi_applicati>
      <id_corso>CRS01</id_corso>
      <id_corso>CRS03</id_corso>
    </corsi_applicati>
  </promozione>
  <promozione id_promo="PR_179308953762">
    <titolo>Crediti Anzianità</titolo>
    <tipo>bonus</tipo>
    <valore>25</valore>
    <criterio_applicazione tipo_criterio="anzianita" soglia="3">Clienti con almeno 3 mesi di iscrizione</criterio_applicazione>
    <data_inizio>2026-08-01</data_inizio>
    <data_fine>2027-12-31</data_fine>
    <corsi_applicati>
      <id_corso>CRS01</id_corso>
      <id_corso>CRS02</id_corso>
      <id_corso>CRS03</id_corso>
      <id_corso>CRS04</id_corso>
    </corsi_applicati>
  </promozione>
</elenco_promozioni>
